[package]
name = "tree-sitter-ini"
description = "ini grammar for the tree-sitter parsing library"
version = "1.3.0"
keywords = ["incremental", "parsing", "ini"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/justinmk/tree-sitter-ini"
edition = "2018"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1.0"

[build-dependencies]
cc = "1.0"
