/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  aux_sym_section_name_token1 = 2,
  anon_sym_RBRACK = 3,
  anon_sym_EQ = 4,
  sym_setting_name = 5,
  sym_setting_value = 6,
  aux_sym_comment_token1 = 7,
  aux_sym_comment_token2 = 8,
  sym__eol = 9,
  sym__space = 10,
  sym_document = 11,
  sym_unnamed_section = 12,
  sym_section = 13,
  sym_section_name = 14,
  sym_setting = 15,
  sym_comment = 16,
  aux_sym_document_repeat1 = 17,
  aux_sym_unnamed_section_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [aux_sym_section_name_token1] = "text",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [sym_setting_name] = "setting_name",
  [sym_setting_value] = "setting_value",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "text",
  [sym__eol] = "_eol",
  [sym__space] = "_space",
  [sym_document] = "document",
  [sym_unnamed_section] = "unnamed_section",
  [sym_section] = "section",
  [sym_section_name] = "section_name",
  [sym_setting] = "setting",
  [sym_comment] = "comment",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_unnamed_section_repeat1] = "unnamed_section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [aux_sym_section_name_token1] = aux_sym_section_name_token1,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_setting_name] = sym_setting_name,
  [sym_setting_value] = sym_setting_value,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_section_name_token1,
  [sym__eol] = sym__eol,
  [sym__space] = sym__space,
  [sym_document] = sym_document,
  [sym_unnamed_section] = sym_unnamed_section,
  [sym_section] = sym_section,
  [sym_section_name] = sym_section_name,
  [sym_setting] = sym_setting,
  [sym_comment] = sym_comment,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_unnamed_section_repeat1] = aux_sym_unnamed_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_section_name_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_setting_name] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_unnamed_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_section_name] = {
    .visible = true,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unnamed_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\n', 22,
        '\r', 1,
        '=', 14,
        '[', 10,
        ']', 13,
        '\t', 23,
        ' ', 23,
        '#', 19,
        ';', 19,
      );
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(17);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(20);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '\r') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(18);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '=' &&
          lookahead != '[') ADVANCE(15);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '[') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(15);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_section_name_token1);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_section_name_token1);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_setting_name);
      if (lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '#' &&
          lookahead != ';' &&
          lookahead != '=' &&
          lookahead != '[') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_setting_value);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_setting_value);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_setting_value);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__space);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {(TSStateId)(-1),},
  [25] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [sym__eol] = ACTIONS(5),
    [sym__space] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_document] = STATE(18),
    [sym_unnamed_section] = STATE(3),
    [sym_section] = STATE(14),
    [sym_section_name] = STATE(4),
    [sym_setting] = STATE(10),
    [sym_comment] = STATE(1),
    [aux_sym_document_repeat1] = STATE(5),
    [aux_sym_unnamed_section_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(9),
    [sym_setting_name] = ACTIONS(11),
    [aux_sym_comment_token1] = ACTIONS(3),
    [sym__eol] = ACTIONS(5),
    [sym__space] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      sym_setting_name,
    STATE(2), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_unnamed_section_repeat1,
    STATE(10), 1,
      sym_setting,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [24] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_comment,
    STATE(4), 1,
      sym_section_name,
    STATE(8), 1,
      aux_sym_document_repeat1,
    STATE(14), 1,
      sym_section,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [50] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      sym_setting_name,
    STATE(4), 1,
      sym_comment,
    STATE(6), 1,
      aux_sym_unnamed_section_repeat1,
    STATE(10), 1,
      sym_setting,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(17), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [74] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_section_name,
    STATE(5), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_document_repeat1,
    STATE(14), 1,
      sym_section,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [100] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(11), 1,
      sym_setting_name,
    STATE(6), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_unnamed_section_repeat1,
    STATE(10), 1,
      sym_setting,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [124] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      sym_setting_name,
    STATE(10), 1,
      sym_setting,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(21), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
    STATE(7), 2,
      sym_comment,
      aux_sym_unnamed_section_repeat1,
  [146] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LBRACK,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_section_name,
    STATE(8), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_document_repeat1,
    STATE(14), 1,
      sym_section,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [172] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(28), 1,
      ts_builtin_sym_end,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    STATE(4), 1,
      sym_section_name,
    STATE(14), 1,
      sym_section,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    STATE(9), 2,
      sym_comment,
      aux_sym_document_repeat1,
  [196] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(10), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(33), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_setting_name,
  [212] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(11), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(35), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_setting_name,
  [228] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(12), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(37), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_setting_name,
  [244] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(13), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(39), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      sym_setting_name,
  [260] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(14), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
  [275] = 4,
    ACTIONS(43), 1,
      aux_sym_section_name_token1,
    ACTIONS(45), 1,
      aux_sym_comment_token1,
    STATE(15), 1,
      sym_comment,
    ACTIONS(47), 2,
      sym__eol,
      sym__space,
  [289] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(49), 1,
      anon_sym_EQ,
    STATE(16), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [303] = 5,
    ACTIONS(45), 1,
      aux_sym_comment_token1,
    ACTIONS(47), 1,
      sym__space,
    ACTIONS(51), 1,
      aux_sym_comment_token2,
    ACTIONS(53), 1,
      sym__eol,
    STATE(17), 1,
      sym_comment,
  [319] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [333] = 5,
    ACTIONS(45), 1,
      aux_sym_comment_token1,
    ACTIONS(47), 1,
      sym__space,
    ACTIONS(57), 1,
      sym_setting_value,
    ACTIONS(59), 1,
      sym__eol,
    STATE(19), 1,
      sym_comment,
  [349] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(61), 1,
      anon_sym_RBRACK,
    STATE(20), 1,
      sym_comment,
    ACTIONS(5), 2,
      sym__eol,
      sym__space,
  [363] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(63), 1,
      sym__eol,
    STATE(21), 1,
      sym_comment,
  [376] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(65), 1,
      sym__eol,
    STATE(22), 1,
      sym_comment,
  [389] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(5), 1,
      sym__space,
    ACTIONS(67), 1,
      sym__eol,
    STATE(23), 1,
      sym_comment,
  [402] = 1,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
  [406] = 1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 50,
  [SMALL_STATE(5)] = 74,
  [SMALL_STATE(6)] = 100,
  [SMALL_STATE(7)] = 124,
  [SMALL_STATE(8)] = 146,
  [SMALL_STATE(9)] = 172,
  [SMALL_STATE(10)] = 196,
  [SMALL_STATE(11)] = 212,
  [SMALL_STATE(12)] = 228,
  [SMALL_STATE(13)] = 244,
  [SMALL_STATE(14)] = 260,
  [SMALL_STATE(15)] = 275,
  [SMALL_STATE(16)] = 289,
  [SMALL_STATE(17)] = 303,
  [SMALL_STATE(18)] = 319,
  [SMALL_STATE(19)] = 333,
  [SMALL_STATE(20)] = 349,
  [SMALL_STATE(21)] = 363,
  [SMALL_STATE(22)] = 376,
  [SMALL_STATE(23)] = 389,
  [SMALL_STATE(24)] = 402,
  [SMALL_STATE(25)] = 406,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unnamed_section, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unnamed_section_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unnamed_section_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unnamed_section_repeat1, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 4, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_name, 4, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [55] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_ini(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "ini",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 1,
      .minor_version = 4,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
